<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings><AssemblyName>Checkit</AssemblyName><Version>0.2.2</Version><ApplicationIcon>Assets/checkit.ico</ApplicationIcon></PropertyGroup><ItemGroup><Resource Include="Assets/checkit.ico" /></ItemGroup></Project>
